spring:
  application:
    name: auth-service

server:
  port: 8001  # Port for Auth Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://<eureka-server-ip>:8761/eureka/
    instance:
      preferIpAddress: 13.201.178.199 # Use IP address instead of hostname for registration
